//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicParam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicParam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CLSDFOLD {
            get {
                object obj = ResourceManager.GetObject("CLSDFOLD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap COMPONENT {
            get {
                object obj = ResourceManager.GetObject("COMPONENT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DEFAULTTHUMBNAIL {
            get {
                object obj = ResourceManager.GetObject("DEFAULTTHUMBNAIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DOC {
            get {
                object obj = ResourceManager.GetObject("DOC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DXF {
            get {
                object obj = ResourceManager.GetObject("DXF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}....
        /// </summary>
        internal static string ID_ABOUT {
            get {
                return ResourceManager.GetString("ID_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will now exit....
        /// </summary>
        internal static string ID_APPLICATIONEXITING {
            get {
                return ResourceManager.GetString("ID_APPLICATIONEXITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will need to be restarted. Now closing....
        /// </summary>
        internal static string ID_APPLICATIONMUSTRESTART {
            get {
                return ResourceManager.GetString("ID_APPLICATIONMUSTRESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model constains more than {0} segments. Processing will require too much time.  To increase maximum number of segments, use Tools&gt;Options&gt;Computing options....
        /// </summary>
        internal static string ID_CANCELTOOLONG {
            get {
                return ResourceManager.GetString("ID_CANCELTOOLONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to clear the database content. Are you sure?.
        /// </summary>
        internal static string ID_CLEARDATABASEWARNING {
            get {
                return ResourceManager.GetString("ID_CLEARDATABASEWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file could not be found at the following path: {0}\n Would you like to restore a database archive?.
        /// </summary>
        internal static string ID_DATABASENOTFOUND {
            get {
                return ResourceManager.GetString("ID_DATABASENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents sharing the same position in the tree than those available in the library will be overwritten.\nAny modifications will be lost. Continue?.
        /// </summary>
        internal static string ID_DATABASEOVERWRITE {
            get {
                return ResourceManager.GetString("ID_DATABASEOVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit component {0}....
        /// </summary>
        internal static string ID_EDITCOMPONENT {
            get {
                return ResourceManager.GetString("ID_EDITCOMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default image file could not be found at the following path: {0}.
        /// </summary>
        internal static string ID_FILENOTFOUND_DEFAULTIMAGE {
            get {
                return ResourceManager.GetString("ID_FILENOTFOUND_DEFAULTIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf thumb image file could not be found at the following path: {0}.
        /// </summary>
        internal static string ID_FILENOTFOUND_PDFTHUMBNAILIMAGE {
            get {
                return ResourceManager.GetString("ID_FILENOTFOUND_PDFTHUMBNAILIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to merge database for the following reason: {0}.
        /// </summary>
        internal static string ID_MERGEFAILURE {
            get {
                return ResourceManager.GetString("ID_MERGEFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore database for the following reason: {0}.
        /// </summary>
        internal static string ID_RESTOREFAILURE {
            get {
                return ResourceManager.GetString("ID_RESTOREFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, be aware that this operation will overwrite your current database. Continue?.
        /// </summary>
        internal static string ID_RESTOREWARNING {
            get {
                return ResourceManager.GetString("ID_RESTOREWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup branch {0}.
        /// </summary>
        internal static string ID_TREEMENUBACKUP {
            get {
                return ResourceManager.GetString("ID_TREEMENUBACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ID_TREEMENUDELETE {
            get {
                return ResourceManager.GetString("ID_TREEMENUDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New branch....
        /// </summary>
        internal static string ID_TREEMENUNEWBRANCH {
            get {
                return ResourceManager.GetString("ID_TREEMENUNEWBRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document....
        /// </summary>
        internal static string ID_TREEMENUNEWDOCUMENT {
            get {
                return ResourceManager.GetString("ID_TREEMENUNEWDOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename....
        /// </summary>
        internal static string ID_TREEMENURENAME {
            get {
                return ResourceManager.GetString("ID_TREEMENURENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node {0} can not be moved under node {1} as this last one is a child.  .
        /// </summary>
        internal static string ID_TREEWARNING_CANNOTMOVENODE {
            get {
                return ResourceManager.GetString("ID_TREEWARNING_CANNOTMOVENODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete branch {0}?.
        /// </summary>
        internal static string ID_TREEWARNING_DELETEBRANCH {
            get {
                return ResourceManager.GetString("ID_TREEWARNING_DELETEBRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document {0}?.
        /// </summary>
        internal static string ID_TREEWARNING_DELETEDOCUMENT {
            get {
                return ResourceManager.GetString("ID_TREEWARNING_DELETEDOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to move node &quot;{0}&quot; under node &quot;{1}&quot;?.
        /// </summary>
        internal static string ID_TREEWARNING_MOVENODE {
            get {
                return ResourceManager.GetString("ID_TREEWARNING_MOVENODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string ID_VERSION {
            get {
                return ResourceManager.GetString("ID_VERSION", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap OPENFOLD {
            get {
                object obj = ResourceManager.GetObject("OPENFOLD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PDF {
            get {
                object obj = ResourceManager.GetObject("PDF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PicParamAbout {
            get {
                object obj = ResourceManager.GetObject("PicParamAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
