//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackLib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardboardProfile
    {
        public CardboardProfile()
        {
            this.CardboardQualities = new HashSet<CardboardQuality>();
            this.MajorationSets = new HashSet<MajorationSet>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public double Thickness { get; set; }
    
        public virtual ICollection<CardboardQuality> CardboardQualities { get; set; }
        public virtual ICollection<MajorationSet> MajorationSets { get; set; }
    }
}
