//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMPackLib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Components = new HashSet<Component>();
            this.TreeNodeDocuments = new HashSet<TreeNodeDocument>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DocumentTypeID { get; set; }
        public int FileID { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual ICollection<Component> Components { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual File File { get; set; }
        public virtual ICollection<TreeNodeDocument> TreeNodeDocuments { get; set; }
    }
}
