//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pic.Factory2D.Control.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal ImpositionMarginTopBottom {
            get {
                return ((decimal)(this["ImpositionMarginTopBottom"]));
            }
            set {
                this["ImpositionMarginTopBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal ImpositionMarginLeftRight {
            get {
                return ((decimal)(this["ImpositionMarginLeftRight"]));
            }
            set {
                this["ImpositionMarginLeftRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboTopBottomIndex {
            get {
                return ((int)(this["ComboTopBottomIndex"]));
            }
            set {
                this["ComboTopBottomIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboLeftRightIndex {
            get {
                return ((int)(this["ComboLeftRightIndex"]));
            }
            set {
                this["ComboLeftRightIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ImpositionCarboardFormat {
            get {
                return ((int)(this["ImpositionCarboardFormat"]));
            }
            set {
                this["ImpositionCarboardFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal ImpositionSpaceBetween {
            get {
                return ((decimal)(this["ImpositionSpaceBetween"]));
            }
            set {
                this["ImpositionSpaceBetween"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal ImpositionRemainingMarginTopBottom {
            get {
                return ((decimal)(this["ImpositionRemainingMarginTopBottom"]));
            }
            set {
                this["ImpositionRemainingMarginTopBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal ImpositionRemainingMarginLeftRight {
            get {
                return ((decimal)(this["ImpositionRemainingMarginLeftRight"]));
            }
            set {
                this["ImpositionRemainingMarginLeftRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileExportDirectory {
            get {
                return ((string)(this["FileExportDirectory"]));
            }
            set {
                this["FileExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileOutputAppDXF {
            get {
                return ((string)(this["FileOutputAppDXF"]));
            }
            set {
                this["FileOutputAppDXF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileOutputAppAI {
            get {
                return ((string)(this["FileOutputAppAI"]));
            }
            set {
                this["FileOutputAppAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileOutputAppCF2 {
            get {
                return ((string)(this["FileOutputAppCF2"]));
            }
            set {
                this["FileOutputAppCF2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wpicador\\Bin32\\PicGEOM.exe")]
        public string FileOutputAppDES {
            get {
                return ((string)(this["FileOutputAppDES"]));
            }
            set {
                this["FileOutputAppDES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wpicador\\Bin\\Picador3D.exe")]
        public string FileOutputAppPic3DDES {
            get {
                return ((string)(this["FileOutputAppPic3DDES"]));
            }
            set {
                this["FileOutputAppPic3DDES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wpicador\\Bin32\\PDecoup.exe")]
        public string FileOutputAppPicDecoupeDES {
            get {
                return ((string)(this["FileOutputAppPicDecoupeDES"]));
            }
            set {
                this["FileOutputAppPicDecoupeDES"] = value;
            }
        }
    }
}
